name: Build and deploy Python app to Azure Web App - dream21

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v3
        with:
          python-version: '3.10.5'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate || . venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Zip artifact for deployment
        run: zip -r $GITHUB_WORKSPACE/release.zip

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: $GITHUB_WORKSPACE/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ needs.build.outputs.artifacts_path }}/release.zip

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app
          path: $GITHUB_WORKSPACE

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'dream21'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_10EC9E161983422B8927704995ABC641 }}
